apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: njjxne8ib-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/njjxne8ib-dotnet-basic-gitops